spring:
  profiles:
    active: local
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true