spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  profiles:
    active: local
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none

server:
  tomcat:
    max-http-form-post-size: 52428800
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
