spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:~/Auta
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true