spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

jwt:
  secret-key: 759428D57A271868FF889A23A593A759428D57A271868FF889A23A593A

cloud:
  aws:
    credentials:
      access-key: dummy
      secret-key: dummy
    s3:
      bucket: dummy-bucket
    region:
      static: ap-northeast-2