name: Build and Deploy API Docs

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build API Docs
        run: ./gradlew clean build asciidoctor

      - name: Save generated docs
        run: |
          mkdir -p tmp-docs
          cp -r build/docs/asciidoc/* tmp-docs/

      - name: Checkout docs branch
        run: |
          git fetch origin docs
          git checkout docs

      - name: Clear old docs and copy new docs
        run: |
          rm -rf *
          cp -r ../tmp-docs/* .
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update API Docs from dev branch" || echo "No changes to commit"
          git push origin docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}